## Prevent user to see and access files and folder
forbidden:
  - _internal
  - vendor

## Hide a folder from the user but doesn't prevent access
hidden:

## List of enabled file previews
enabled_previews:
  - image
  - video
  - code
  - audio
  - markdown

## Do we preview the README if one is present
enabled_readme: true

## Settings for specific file previews
previews:
  code:
    ## Enables code preview for files that might be considered unsafe such as .php
    unsafe: false

displays:
## Choose how the content of a folder is displayed
## Example:
## "path/to/folder":
##  format: image ## Possible values: none, image
##  displayOthers: false ## If format not none, do we display the files that can't be previewed
##  displayBack: false ## Do we display the "back" folder
