## Prevent user to see and access files and folder
forbidden:
  - _internal
  - vendor

## Hide a folder from the user but doesn't prevent access
hidden:

## List of enabled file previews
enabled_previews:
  - image
  - video
  - code
  - audio
  - markdown

## Settings for specific file previews
previews:
  code:
    ## Enables code preview for files that might be considered unsafe such as .php
    unsafe: false

displays:
  ## Choose how the content of a folder is displayed
  ## Format: "path/to/folder": displayMode
  ## Displays possible values: none, image
  "publish/demo": image